In [4]:
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 682.7 kB/s eta 0:00:01
     ------------- ------------------------ 20.5/59.7 kB 682.7 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 525.1 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 317.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.9 MB 1.1 MB/s eta 0:00:12
   ---------------------------------------- 0.1/12.9 MB 1.1 MB/s eta 0:00:12
   ---------------------------------------- 0.1/12.9 MB 651.6 kB/s eta 0:00:20
   ---------------------------------------- 0.1/12.9 MB 476.3 kB/s eta 0:00:27
   ---------------------------------------- 0.1/12.9 MB 504.4 kB/s eta 0:00:

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\vaibh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9])
print(np1)

[1 2 3 4 5 6 7 8 9]


In [7]:
arr = [20, 2, 5, 10, 4] 
print("sum of arr : ", np.sum(arr)) 

sum of arr :  41


In [8]:
arr = [20, 2, 5, 10, 4] 
print("mean of arr :", np.mean(arr)) 


mean of arr : 8.2


In [9]:
import numpy as np
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [13]:
import numpy as np
df=np.zeros(2)
print(df)

[0. 0.]


In [15]:
import numpy as np
x=np.linspace(1,10,10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [16]:
import numpy as np
 
 
# creating array with shape(4,3)
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)
 
# swapping the column with index of 
# original array
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [17]:
import numpy as np
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)  

Along first axis : 
 [[10  1]
 [12 15]]
